spring.application.name=DemoSys

#数据库连接ses-sys
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.url=jdbc:mysql://localhost:3306/ses-sys
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.type=com.alibaba.druid.pool.DruidDataSource

mybatis.configuration.map-underscore-to-camel-case=true

mybatis.mapper-locations=classpath:com/itec/mapper/*.xml

mybatis.type-aliases-package=com.itec.pojo

#返回时间
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+9

logging.level.com.itec.service=DEBUG
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl