package com.itec.mapper;

import com.itec.pojo.Operate;
import com.itec.pojo.OperateKey;

public interface OperateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_OPERATE_TBL
     *
     * @mbg.generated Fri Dec 13 14:58:51 HKT 2024
     */
    int deleteByPrimaryKey(OperateKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_OPERATE_TBL
     *
     * @mbg.generated Fri Dec 13 14:58:51 HKT 2024
     */
    int insert(Operate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_OPERATE_TBL
     *
     * @mbg.generated Fri Dec 13 14:58:51 HKT 2024
     */
    int insertSelective(Operate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_OPERATE_TBL
     *
     * @mbg.generated Fri Dec 13 14:58:51 HKT 2024
     */
    Operate selectByPrimaryKey(OperateKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_OPERATE_TBL
     *
     * @mbg.generated Fri Dec 13 14:58:51 HKT 2024
     */
    int updateByPrimaryKeySelective(Operate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_OPERATE_TBL
     *
     * @mbg.generated Fri Dec 13 14:58:51 HKT 2024
     */
    int updateByPrimaryKey(Operate record);
}