package com.itec.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Select;

import com.itec.pojo.User;

@Mapper
public interface UserMapper {

	// 登录
	@Select("select * from user_tbl where USER_MAILADDRESS =#{userMailaddress} and USER_PWD =#{userPwd} and USER_LOCK_FLG=0 and USER_DEL_FLG=0")
	User login(String userMailaddress, String userPwd);

	// 通过Username、邮箱、权限查找信息
	User selectUserInfo(String userMailaddress, String userNm, Byte userRole);

	// 通过邮箱查找信息
	@Select("select * from user_tbl where USER_MAILADDRESS =#{userMailaddress}  and USER_LOCK_FLG=0 and USER_DEL_FLG=0")
	User selectUserInfoByMail(String userMailaddress);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table user_tbl
	 *
	 * @mbg.generated Thu Nov 14 21:49:59 HKT 2024
	 */
	int deleteByPrimaryKey(String userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table user_tbl
	 *
	 * @mbg.generated Thu Nov 14 21:49:59 HKT 2024
	 */
	int insert(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table user_tbl
	 *
	 * @mbg.generated Thu Nov 14 21:49:59 HKT 2024
	 */
	int insertSelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table user_tbl
	 *
	 * @mbg.generated Thu Nov 14 21:49:59 HKT 2024
	 */
	User selectByPrimaryKey(String userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table user_tbl
	 *
	 * @mbg.generated Thu Nov 14 21:49:59 HKT 2024
	 */
	int updateByPrimaryKeySelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table user_tbl
	 *
	 * @mbg.generated Thu Nov 14 21:49:59 HKT 2024
	 */
	int updateByPrimaryKey(User record);
}