package com.itec.pojo;

public class BillDetlKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLDETL_TBL.BILLDETL_ID
     *
     * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
     */
    private Long billdetlId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BILLDETL_TBL.BILLDETL_NO
     *
     * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
     */
    private String billdetlNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLDETL_TBL.BILLDETL_ID
     *
     * @return the value of BILLDETL_TBL.BILLDETL_ID
     *
     * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
     */
    public Long getBilldetlId() {
        return billdetlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLDETL_TBL.BILLDETL_ID
     *
     * @param billdetlId the value for BILLDETL_TBL.BILLDETL_ID
     *
     * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
     */
    public void setBilldetlId(Long billdetlId) {
        this.billdetlId = billdetlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BILLDETL_TBL.BILLDETL_NO
     *
     * @return the value of BILLDETL_TBL.BILLDETL_NO
     *
     * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
     */
    public String getBilldetlNo() {
        return billdetlNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BILLDETL_TBL.BILLDETL_NO
     *
     * @param billdetlNo the value for BILLDETL_TBL.BILLDETL_NO
     *
     * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
     */
    public void setBilldetlNo(String billdetlNo) {
        this.billdetlNo = billdetlNo;
    }
}