package com.itec.pojo;

import java.util.Date;

public class Bill {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column BILL_TBL.BILL_NO
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	private String billNo;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column BILL_TBL.BILL_NM
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	private String billNm;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column BILL_TBL.BILL_ENGINEER_NM
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	private String billEngineerNm;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column BILL_TBL.BILL_CUST_NM
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	private String billCustNm;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column BILL_TBL.BILL_PROJECT_NM
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	private String billProjectNm;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column BILL_TBL.BILL_STARTDT
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	private Date billStartdt;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column BILL_TBL.BILL_ENDTDT
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	private Date billEndtdt;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column BILL_TBL.BILL_CONFIRMFLG
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	private String billConfirmflg;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column BILL_TBL.BILL_DELFLG
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	private String billDelflg;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column BILL_TBL.BILL_CLS
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	private String billCls;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column BILL_TBL.BILL_STATUS
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	private String billStatus;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column BILL_TBL.BILL_PAYMENT_TERM
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	private Date billPaymentTerm;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column BILL_TBL.BILL_CHARGED_AMOUNT
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	private Integer billChargedAmount;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column BILL_TBL.BILL_TAX_RATE
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	private String billTaxRate;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column BILL_TBL.BILL_AMOUNT_SUBTOTAL
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	private Integer billAmountSubtotal;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column BILL_TBL.BILL_CONSUMPTION_TAX
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	private Integer billConsumptionTax;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column BILL_TBL.BILL_TOTAL_AMOUNT
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	private Integer billTotalAmount;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column BILL_TBL.BILL_RMK
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	private String billRmk;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column BILL_TBL.BILL_CRD_USR
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	private String billCrdUsr;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column BILL_TBL.BILL_CRD_DT
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	private Date billCrdDt;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column BILL_TBL.BILL_UPD_USR
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	private String billUpdUsr;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column BILL_TBL.BILL_UPD_DT
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	private Date billUpdDt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column BILL_TBL.BILL_NO
	 *
	 * @return the value of BILL_TBL.BILL_NO
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public String getBillNo() {
		return billNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column BILL_TBL.BILL_NO
	 *
	 * @param billNo the value for BILL_TBL.BILL_NO
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public void setBillNo(String billNo) {
		this.billNo = billNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column BILL_TBL.BILL_NM
	 *
	 * @return the value of BILL_TBL.BILL_NM
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public String getBillNm() {
		return billNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column BILL_TBL.BILL_NM
	 *
	 * @param billNm the value for BILL_TBL.BILL_NM
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public void setBillNm(String billNm) {
		this.billNm = billNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column BILL_TBL.BILL_ENGINEER_NM
	 *
	 * @return the value of BILL_TBL.BILL_ENGINEER_NM
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public String getBillEngineerNm() {
		return billEngineerNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column BILL_TBL.BILL_ENGINEER_NM
	 *
	 * @param billEngineerNm the value for BILL_TBL.BILL_ENGINEER_NM
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public void setBillEngineerNm(String billEngineerNm) {
		this.billEngineerNm = billEngineerNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column BILL_TBL.BILL_CUST_NM
	 *
	 * @return the value of BILL_TBL.BILL_CUST_NM
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public String getBillCustNm() {
		return billCustNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column BILL_TBL.BILL_CUST_NM
	 *
	 * @param billCustNm the value for BILL_TBL.BILL_CUST_NM
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public void setBillCustNm(String billCustNm) {
		this.billCustNm = billCustNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column BILL_TBL.BILL_PROJECT_NM
	 *
	 * @return the value of BILL_TBL.BILL_PROJECT_NM
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public String getBillProjectNm() {
		return billProjectNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column BILL_TBL.BILL_PROJECT_NM
	 *
	 * @param billProjectNm the value for BILL_TBL.BILL_PROJECT_NM
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public void setBillProjectNm(String billProjectNm) {
		this.billProjectNm = billProjectNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column BILL_TBL.BILL_STARTDT
	 *
	 * @return the value of BILL_TBL.BILL_STARTDT
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public Date getBillStartdt() {
		return billStartdt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column BILL_TBL.BILL_STARTDT
	 *
	 * @param billStartdt the value for BILL_TBL.BILL_STARTDT
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public void setBillStartdt(Date billStartdt) {
		this.billStartdt = billStartdt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column BILL_TBL.BILL_ENDTDT
	 *
	 * @return the value of BILL_TBL.BILL_ENDTDT
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public Date getBillEndtdt() {
		return billEndtdt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column BILL_TBL.BILL_ENDTDT
	 *
	 * @param billEndtdt the value for BILL_TBL.BILL_ENDTDT
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public void setBillEndtdt(Date billEndtdt) {
		this.billEndtdt = billEndtdt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column BILL_TBL.BILL_CONFIRMFLG
	 *
	 * @return the value of BILL_TBL.BILL_CONFIRMFLG
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public String getBillConfirmflg() {
		return billConfirmflg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column BILL_TBL.BILL_CONFIRMFLG
	 *
	 * @param billConfirmflg the value for BILL_TBL.BILL_CONFIRMFLG
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public void setBillConfirmflg(String billConfirmflg) {
		this.billConfirmflg = billConfirmflg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column BILL_TBL.BILL_DELFLG
	 *
	 * @return the value of BILL_TBL.BILL_DELFLG
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public String getBillDelflg() {
		return billDelflg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column BILL_TBL.BILL_DELFLG
	 *
	 * @param billDelflg the value for BILL_TBL.BILL_DELFLG
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public void setBillDelflg(String billDelflg) {
		this.billDelflg = billDelflg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column BILL_TBL.BILL_CLS
	 *
	 * @return the value of BILL_TBL.BILL_CLS
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public String getBillCls() {
		return billCls;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column BILL_TBL.BILL_CLS
	 *
	 * @param billCls the value for BILL_TBL.BILL_CLS
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public void setBillCls(String billCls) {
		this.billCls = billCls;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column BILL_TBL.BILL_STATUS
	 *
	 * @return the value of BILL_TBL.BILL_STATUS
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public String getBillStatus() {
		return billStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column BILL_TBL.BILL_STATUS
	 *
	 * @param billStatus the value for BILL_TBL.BILL_STATUS
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public void setBillStatus(String billStatus) {
		this.billStatus = billStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column BILL_TBL.BILL_PAYMENT_TERM
	 *
	 * @return the value of BILL_TBL.BILL_PAYMENT_TERM
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public Date getBillPaymentTerm() {
		return billPaymentTerm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column BILL_TBL.BILL_PAYMENT_TERM
	 *
	 * @param billPaymentTerm the value for BILL_TBL.BILL_PAYMENT_TERM
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public void setBillPaymentTerm(Date billPaymentTerm) {
		this.billPaymentTerm = billPaymentTerm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column BILL_TBL.BILL_CHARGED_AMOUNT
	 *
	 * @return the value of BILL_TBL.BILL_CHARGED_AMOUNT
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public Integer getBillChargedAmount() {
		return billChargedAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column BILL_TBL.BILL_CHARGED_AMOUNT
	 *
	 * @param billChargedAmount the value for BILL_TBL.BILL_CHARGED_AMOUNT
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public void setBillChargedAmount(Integer billChargedAmount) {
		this.billChargedAmount = billChargedAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column BILL_TBL.BILL_TAX_RATE
	 *
	 * @return the value of BILL_TBL.BILL_TAX_RATE
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public String getBillTaxRate() {
		return billTaxRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column BILL_TBL.BILL_TAX_RATE
	 *
	 * @param billTaxRate the value for BILL_TBL.BILL_TAX_RATE
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public void setBillTaxRate(String billTaxRate) {
		this.billTaxRate = billTaxRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column BILL_TBL.BILL_AMOUNT_SUBTOTAL
	 *
	 * @return the value of BILL_TBL.BILL_AMOUNT_SUBTOTAL
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public Integer getBillAmountSubtotal() {
		return billAmountSubtotal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column BILL_TBL.BILL_AMOUNT_SUBTOTAL
	 *
	 * @param billAmountSubtotal the value for BILL_TBL.BILL_AMOUNT_SUBTOTAL
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public void setBillAmountSubtotal(Integer billAmountSubtotal) {
		this.billAmountSubtotal = billAmountSubtotal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column BILL_TBL.BILL_CONSUMPTION_TAX
	 *
	 * @return the value of BILL_TBL.BILL_CONSUMPTION_TAX
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public Integer getBillConsumptionTax() {
		return billConsumptionTax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column BILL_TBL.BILL_CONSUMPTION_TAX
	 *
	 * @param billConsumptionTax the value for BILL_TBL.BILL_CONSUMPTION_TAX
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public void setBillConsumptionTax(Integer billConsumptionTax) {
		this.billConsumptionTax = billConsumptionTax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column BILL_TBL.BILL_TOTAL_AMOUNT
	 *
	 * @return the value of BILL_TBL.BILL_TOTAL_AMOUNT
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public Integer getBillTotalAmount() {
		return billTotalAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column BILL_TBL.BILL_TOTAL_AMOUNT
	 *
	 * @param billTotalAmount the value for BILL_TBL.BILL_TOTAL_AMOUNT
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public void setBillTotalAmount(Integer billTotalAmount) {
		this.billTotalAmount = billTotalAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column BILL_TBL.BILL_RMK
	 *
	 * @return the value of BILL_TBL.BILL_RMK
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public String getBillRmk() {
		return billRmk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column BILL_TBL.BILL_RMK
	 *
	 * @param billRmk the value for BILL_TBL.BILL_RMK
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public void setBillRmk(String billRmk) {
		this.billRmk = billRmk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column BILL_TBL.BILL_CRD_USR
	 *
	 * @return the value of BILL_TBL.BILL_CRD_USR
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public String getBillCrdUsr() {
		return billCrdUsr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column BILL_TBL.BILL_CRD_USR
	 *
	 * @param billCrdUsr the value for BILL_TBL.BILL_CRD_USR
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public void setBillCrdUsr(String billCrdUsr) {
		this.billCrdUsr = billCrdUsr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column BILL_TBL.BILL_CRD_DT
	 *
	 * @return the value of BILL_TBL.BILL_CRD_DT
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public Date getBillCrdDt() {
		return billCrdDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column BILL_TBL.BILL_CRD_DT
	 *
	 * @param billCrdDt the value for BILL_TBL.BILL_CRD_DT
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public void setBillCrdDt(Date billCrdDt) {
		this.billCrdDt = billCrdDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column BILL_TBL.BILL_UPD_USR
	 *
	 * @return the value of BILL_TBL.BILL_UPD_USR
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public String getBillUpdUsr() {
		return billUpdUsr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column BILL_TBL.BILL_UPD_USR
	 *
	 * @param billUpdUsr the value for BILL_TBL.BILL_UPD_USR
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public void setBillUpdUsr(String billUpdUsr) {
		this.billUpdUsr = billUpdUsr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column BILL_TBL.BILL_UPD_DT
	 *
	 * @return the value of BILL_TBL.BILL_UPD_DT
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public Date getBillUpdDt() {
		return billUpdDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column BILL_TBL.BILL_UPD_DT
	 *
	 * @param billUpdDt the value for BILL_TBL.BILL_UPD_DT
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public void setBillUpdDt(Date billUpdDt) {
		this.billUpdDt = billUpdDt;
	}

	public Bill(String billNo, String billNm, String billEngineerNm, String billCustNm, String billProjectNm,
			Date billStartdt, Date billEndtdt, String billConfirmflg, String billDelflg, String billCls,
			String billStatus, Date billPaymentTerm, Integer billChargedAmount, String billTaxRate,
			Integer billAmountSubtotal, Integer billConsumptionTax, Integer billTotalAmount, String billRmk,
			String billCrdUsr, Date billCrdDt, String billUpdUsr, Date billUpdDt) {
		super();
		this.billNo = billNo;
		this.billNm = billNm;
		this.billEngineerNm = billEngineerNm;
		this.billCustNm = billCustNm;
		this.billProjectNm = billProjectNm;
		this.billStartdt = billStartdt;
		this.billEndtdt = billEndtdt;
		this.billConfirmflg = billConfirmflg;
		this.billDelflg = billDelflg;
		this.billCls = billCls;
		this.billStatus = billStatus;
		this.billPaymentTerm = billPaymentTerm;
		this.billChargedAmount = billChargedAmount;
		this.billTaxRate = billTaxRate;
		this.billAmountSubtotal = billAmountSubtotal;
		this.billConsumptionTax = billConsumptionTax;
		this.billTotalAmount = billTotalAmount;
		this.billRmk = billRmk;
		this.billCrdUsr = billCrdUsr;
		this.billCrdDt = billCrdDt;
		this.billUpdUsr = billUpdUsr;
		this.billUpdDt = billUpdDt;
	}

	public Bill() {
		super();
	}

}