package com.itec.pojo;

import java.util.Date;

public class BillDetl extends BillDetlKey {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column BILLDETL_TBL.BILLDETL_ENGINEER_NM
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	private String billdetlEngineerNm;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column BILLDETL_TBL.BILLDETL_PRICE_PER
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	private Integer billdetlPricePer;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column BILLDETL_TBL.BILLDETL_AMOUNT
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	private Integer billdetlAmount;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column BILLDETL_TBL.BILLDETL_DEDU_TIME
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	private Integer billdetlDeduTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column BILLDETL_TBL.BILLDETL_EXCESS_TIME
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	private Integer billdetlExcessTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column BILLDETL_TBL.BILLDETL_DEDU_UNITPRICE
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	private Integer billdetlDeduUnitprice;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column BILLDETL_TBL.BILLDETL_EXCESS_UNITPRICE
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	private Integer billdetlExcessUnitprice;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column BILLDETL_TBL.BILLDETL_PRETAXAMO
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	private Integer billdetlPretaxamo;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column BILLDETL_TBL.BILLDETL_TRANS_EXPENSES
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	private Integer billdetlTransExpenses;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column BILLDETL_TBL.BILLDETL_TOTALAMO
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	private Integer billdetlTotalamo;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column BILLDETL_TBL.BILLDETL_RMK
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	private String billdetlRmk;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column BILLDETL_TBL.BILLDETL_CRD_USR
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	private String billdetlCrdUsr;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column BILLDETL_TBL.BILLDETL_CRD_DT
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	private Date billdetlCrdDt;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column BILLDETL_TBL.BILLDETL_UPD_USR
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	private String billdetlUpdUsr;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column BILLDETL_TBL.BILLDETL_UPD_DT
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	private Date billdetlUpdDt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column BILLDETL_TBL.BILLDETL_ENGINEER_NM
	 *
	 * @return the value of BILLDETL_TBL.BILLDETL_ENGINEER_NM
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public String getBilldetlEngineerNm() {
		return billdetlEngineerNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column BILLDETL_TBL.BILLDETL_ENGINEER_NM
	 *
	 * @param billdetlEngineerNm the value for BILLDETL_TBL.BILLDETL_ENGINEER_NM
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public void setBilldetlEngineerNm(String billdetlEngineerNm) {
		this.billdetlEngineerNm = billdetlEngineerNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column BILLDETL_TBL.BILLDETL_PRICE_PER
	 *
	 * @return the value of BILLDETL_TBL.BILLDETL_PRICE_PER
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public Integer getBilldetlPricePer() {
		return billdetlPricePer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column BILLDETL_TBL.BILLDETL_PRICE_PER
	 *
	 * @param billdetlPricePer the value for BILLDETL_TBL.BILLDETL_PRICE_PER
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public void setBilldetlPricePer(Integer billdetlPricePer) {
		this.billdetlPricePer = billdetlPricePer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column BILLDETL_TBL.BILLDETL_AMOUNT
	 *
	 * @return the value of BILLDETL_TBL.BILLDETL_AMOUNT
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public Integer getBilldetlAmount() {
		return billdetlAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column BILLDETL_TBL.BILLDETL_AMOUNT
	 *
	 * @param billdetlAmount the value for BILLDETL_TBL.BILLDETL_AMOUNT
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public void setBilldetlAmount(Integer billdetlAmount) {
		this.billdetlAmount = billdetlAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column BILLDETL_TBL.BILLDETL_DEDU_TIME
	 *
	 * @return the value of BILLDETL_TBL.BILLDETL_DEDU_TIME
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public Integer getBilldetlDeduTime() {
		return billdetlDeduTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column BILLDETL_TBL.BILLDETL_DEDU_TIME
	 *
	 * @param billdetlDeduTime the value for BILLDETL_TBL.BILLDETL_DEDU_TIME
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public void setBilldetlDeduTime(Integer billdetlDeduTime) {
		this.billdetlDeduTime = billdetlDeduTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column BILLDETL_TBL.BILLDETL_EXCESS_TIME
	 *
	 * @return the value of BILLDETL_TBL.BILLDETL_EXCESS_TIME
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public Integer getBilldetlExcessTime() {
		return billdetlExcessTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column BILLDETL_TBL.BILLDETL_EXCESS_TIME
	 *
	 * @param billdetlExcessTime the value for BILLDETL_TBL.BILLDETL_EXCESS_TIME
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public void setBilldetlExcessTime(Integer billdetlExcessTime) {
		this.billdetlExcessTime = billdetlExcessTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column BILLDETL_TBL.BILLDETL_DEDU_UNITPRICE
	 *
	 * @return the value of BILLDETL_TBL.BILLDETL_DEDU_UNITPRICE
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public Integer getBilldetlDeduUnitprice() {
		return billdetlDeduUnitprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column BILLDETL_TBL.BILLDETL_DEDU_UNITPRICE
	 *
	 * @param billdetlDeduUnitprice the value for
	 *                              BILLDETL_TBL.BILLDETL_DEDU_UNITPRICE
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public void setBilldetlDeduUnitprice(Integer billdetlDeduUnitprice) {
		this.billdetlDeduUnitprice = billdetlDeduUnitprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column BILLDETL_TBL.BILLDETL_EXCESS_UNITPRICE
	 *
	 * @return the value of BILLDETL_TBL.BILLDETL_EXCESS_UNITPRICE
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public Integer getBilldetlExcessUnitprice() {
		return billdetlExcessUnitprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column BILLDETL_TBL.BILLDETL_EXCESS_UNITPRICE
	 *
	 * @param billdetlExcessUnitprice the value for
	 *                                BILLDETL_TBL.BILLDETL_EXCESS_UNITPRICE
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public void setBilldetlExcessUnitprice(Integer billdetlExcessUnitprice) {
		this.billdetlExcessUnitprice = billdetlExcessUnitprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column BILLDETL_TBL.BILLDETL_PRETAXAMO
	 *
	 * @return the value of BILLDETL_TBL.BILLDETL_PRETAXAMO
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public Integer getBilldetlPretaxamo() {
		return billdetlPretaxamo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column BILLDETL_TBL.BILLDETL_PRETAXAMO
	 *
	 * @param billdetlPretaxamo the value for BILLDETL_TBL.BILLDETL_PRETAXAMO
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public void setBilldetlPretaxamo(Integer billdetlPretaxamo) {
		this.billdetlPretaxamo = billdetlPretaxamo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column BILLDETL_TBL.BILLDETL_TRANS_EXPENSES
	 *
	 * @return the value of BILLDETL_TBL.BILLDETL_TRANS_EXPENSES
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public Integer getBilldetlTransExpenses() {
		return billdetlTransExpenses;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column BILLDETL_TBL.BILLDETL_TRANS_EXPENSES
	 *
	 * @param billdetlTransExpenses the value for
	 *                              BILLDETL_TBL.BILLDETL_TRANS_EXPENSES
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public void setBilldetlTransExpenses(Integer billdetlTransExpenses) {
		this.billdetlTransExpenses = billdetlTransExpenses;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column BILLDETL_TBL.BILLDETL_TOTALAMO
	 *
	 * @return the value of BILLDETL_TBL.BILLDETL_TOTALAMO
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public Integer getBilldetlTotalamo() {
		return billdetlTotalamo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column BILLDETL_TBL.BILLDETL_TOTALAMO
	 *
	 * @param billdetlTotalamo the value for BILLDETL_TBL.BILLDETL_TOTALAMO
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public void setBilldetlTotalamo(Integer billdetlTotalamo) {
		this.billdetlTotalamo = billdetlTotalamo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column BILLDETL_TBL.BILLDETL_RMK
	 *
	 * @return the value of BILLDETL_TBL.BILLDETL_RMK
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public String getBilldetlRmk() {
		return billdetlRmk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column BILLDETL_TBL.BILLDETL_RMK
	 *
	 * @param billdetlRmk the value for BILLDETL_TBL.BILLDETL_RMK
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public void setBilldetlRmk(String billdetlRmk) {
		this.billdetlRmk = billdetlRmk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column BILLDETL_TBL.BILLDETL_CRD_USR
	 *
	 * @return the value of BILLDETL_TBL.BILLDETL_CRD_USR
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public String getBilldetlCrdUsr() {
		return billdetlCrdUsr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column BILLDETL_TBL.BILLDETL_CRD_USR
	 *
	 * @param billdetlCrdUsr the value for BILLDETL_TBL.BILLDETL_CRD_USR
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public void setBilldetlCrdUsr(String billdetlCrdUsr) {
		this.billdetlCrdUsr = billdetlCrdUsr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column BILLDETL_TBL.BILLDETL_CRD_DT
	 *
	 * @return the value of BILLDETL_TBL.BILLDETL_CRD_DT
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public Date getBilldetlCrdDt() {
		return billdetlCrdDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column BILLDETL_TBL.BILLDETL_CRD_DT
	 *
	 * @param billdetlCrdDt the value for BILLDETL_TBL.BILLDETL_CRD_DT
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public void setBilldetlCrdDt(Date billdetlCrdDt) {
		this.billdetlCrdDt = billdetlCrdDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column BILLDETL_TBL.BILLDETL_UPD_USR
	 *
	 * @return the value of BILLDETL_TBL.BILLDETL_UPD_USR
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public String getBilldetlUpdUsr() {
		return billdetlUpdUsr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column BILLDETL_TBL.BILLDETL_UPD_USR
	 *
	 * @param billdetlUpdUsr the value for BILLDETL_TBL.BILLDETL_UPD_USR
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public void setBilldetlUpdUsr(String billdetlUpdUsr) {
		this.billdetlUpdUsr = billdetlUpdUsr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column BILLDETL_TBL.BILLDETL_UPD_DT
	 *
	 * @return the value of BILLDETL_TBL.BILLDETL_UPD_DT
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public Date getBilldetlUpdDt() {
		return billdetlUpdDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column BILLDETL_TBL.BILLDETL_UPD_DT
	 *
	 * @param billdetlUpdDt the value for BILLDETL_TBL.BILLDETL_UPD_DT
	 *
	 * @mbg.generated Fri Jan 03 13:11:56 HKT 2025
	 */
	public void setBilldetlUpdDt(Date billdetlUpdDt) {
		this.billdetlUpdDt = billdetlUpdDt;
	}

	public BillDetl(String billdetlEngineerNm, Integer billdetlPricePer, Integer billdetlAmount,
			Integer billdetlDeduTime, Integer billdetlExcessTime, Integer billdetlDeduUnitprice,
			Integer billdetlExcessUnitprice, Integer billdetlPretaxamo, Integer billdetlTransExpenses,
			Integer billdetlTotalamo, String billdetlRmk, String billdetlCrdUsr, Date billdetlCrdDt,
			String billdetlUpdUsr, Date billdetlUpdDt) {
		super();
		this.billdetlEngineerNm = billdetlEngineerNm;
		this.billdetlPricePer = billdetlPricePer;
		this.billdetlAmount = billdetlAmount;
		this.billdetlDeduTime = billdetlDeduTime;
		this.billdetlExcessTime = billdetlExcessTime;
		this.billdetlDeduUnitprice = billdetlDeduUnitprice;
		this.billdetlExcessUnitprice = billdetlExcessUnitprice;
		this.billdetlPretaxamo = billdetlPretaxamo;
		this.billdetlTransExpenses = billdetlTransExpenses;
		this.billdetlTotalamo = billdetlTotalamo;
		this.billdetlRmk = billdetlRmk;
		this.billdetlCrdUsr = billdetlCrdUsr;
		this.billdetlCrdDt = billdetlCrdDt;
		this.billdetlUpdUsr = billdetlUpdUsr;
		this.billdetlUpdDt = billdetlUpdDt;
	}

	public BillDetl() {
		super();
	}

}