package com.itec.pojo;

import java.time.LocalDateTime;

import org.springframework.stereotype.Component;

@Component
public class CustInfo {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cust_tbl.CUST_ID
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	private String custId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cust_tbl.CUST_NM
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	private String custNm;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cust_tbl.CUST_KN
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	private String custKn;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cust_tbl.CUST_PHONE
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	private String custPhone;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cust_tbl.CUST_DELFLG
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	private boolean custDelflg;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cust_tbl.CUST_FAX
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	private String custFax;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cust_tbl.CUST_WEB
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	private String custWeb;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cust_tbl.CUST_POSTNO
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	private String custPostno;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cust_tbl.CUST_ADDRESS
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	private String custAddress;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cust_tbl.CUST_TYPE
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	private String custType;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cust_tbl.CUST_MONEY
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	private String custMoney;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cust_tbl.CUST_INVOICE_NO
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	private String custInvoiceNo;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cust_tbl.CUST_INFOR_SECURITY
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	private boolean custInforSecurity;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cust_tbl.CUST_DISPATCH
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	private boolean custDispatch;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cust_tbl.CUST_EMPNUM
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	private Integer custEmpnum;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cust_tbl.CUST_STARTDT
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	private LocalDateTime custStartdt;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cust_tbl.CUST_ANNUALSALE
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	private String custAnnualsale;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cust_tbl.CUST_COMPANYREP
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	private String custCompanyrep;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cust_tbl.CUST_RMK1
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	private String custRmk1;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cust_tbl.CUST_RMK2
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	private String custRmk2;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cust_tbl.CUST_CLOSEDT
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	private String custClosedt;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cust_tbl.CUST_PAYDT
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	private String custPaydt;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cust_tbl.CUST_ORDERDT
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	private String custOrderdt;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cust_tbl.CUST_GETDT
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	private String custGetdt;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cust_tbl.CUST_GETCDT
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	private String custGetcdt;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cust_tbl.CUST_ORDERGDT
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	private String custOrdergdt;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cust_tbl.BANK_CD
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	private String bankCd;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cust_tbl.BANK_CHRCD
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	private String bankChrcd;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cust_tbl.CUST_BANK_NM
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	private String custBankNm;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cust_tbl.CUST_BRANCH_CD
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	private String custBranchNm;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cust_tbl.CUST_DEPOSITTYPE
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	private String custDeposittype;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cust_tbl.CUST_BRANCHCD
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	private String custBranchCd;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cust_tbl.CUST_ACCOUNTNO
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	private Integer custAccountno;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cust_tbl.CUST_NOMINEE
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	private String custNominee;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cust_tbl.CUST_CRD_USR
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	private String custCrdUsr;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cust_tbl.CUST_CRD_DT
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	private LocalDateTime custCrdDt;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cust_tbl.CUST_UPD_USR
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	private String custUpdUsr;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cust_tbl.CUST_UPD_DT
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	private LocalDateTime custUpdDt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cust_tbl.CUST_ID
	 *
	 * @return the value of cust_tbl.CUST_ID
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public String getCustId() {
		return custId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cust_tbl.CUST_ID
	 *
	 * @param custId the value for cust_tbl.CUST_ID
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public void setCustId(String custId) {
		this.custId = custId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cust_tbl.CUST_NM
	 *
	 * @return the value of cust_tbl.CUST_NM
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public String getCustNm() {
		return custNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cust_tbl.CUST_NM
	 *
	 * @param custNm the value for cust_tbl.CUST_NM
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public void setCustNm(String custNm) {
		this.custNm = custNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cust_tbl.CUST_KN
	 *
	 * @return the value of cust_tbl.CUST_KN
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public String getCustKn() {
		return custKn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cust_tbl.CUST_KN
	 *
	 * @param custKn the value for cust_tbl.CUST_KN
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public void setCustKn(String custKn) {
		this.custKn = custKn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cust_tbl.CUST_PHONE
	 *
	 * @return the value of cust_tbl.CUST_PHONE
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public String getCustPhone() {
		return custPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cust_tbl.CUST_PHONE
	 *
	 * @param custPhone the value for cust_tbl.CUST_PHONE
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public void setCustPhone(String custPhone) {
		this.custPhone = custPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cust_tbl.CUST_DELFLG
	 *
	 * @return the value of cust_tbl.CUST_DELFLG
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public boolean getCustDelflg() {
		return custDelflg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cust_tbl.CUST_DELFLG
	 *
	 * @param custDelflg the value for cust_tbl.CUST_DELFLG
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public void setCustDelflg(boolean custDelflg) {
		this.custDelflg = custDelflg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cust_tbl.CUST_FAX
	 *
	 * @return the value of cust_tbl.CUST_FAX
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public String getCustFax() {
		return custFax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cust_tbl.CUST_FAX
	 *
	 * @param custFax the value for cust_tbl.CUST_FAX
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public void setCustFax(String custFax) {
		this.custFax = custFax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cust_tbl.CUST_WEB
	 *
	 * @return the value of cust_tbl.CUST_WEB
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public String getCustWeb() {
		return custWeb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cust_tbl.CUST_WEB
	 *
	 * @param custWeb the value for cust_tbl.CUST_WEB
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public void setCustWeb(String custWeb) {
		this.custWeb = custWeb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cust_tbl.CUST_POSTNO
	 *
	 * @return the value of cust_tbl.CUST_POSTNO
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public String getCustPostno() {
		return custPostno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cust_tbl.CUST_POSTNO
	 *
	 * @param custPostno the value for cust_tbl.CUST_POSTNO
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public void setCustPostno(String custPostno) {
		this.custPostno = custPostno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cust_tbl.CUST_ADDRESS
	 *
	 * @return the value of cust_tbl.CUST_ADDRESS
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public String getCustAddress() {
		return custAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cust_tbl.CUST_ADDRESS
	 *
	 * @param custAddress the value for cust_tbl.CUST_ADDRESS
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public void setCustAddress(String custAddress) {
		this.custAddress = custAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cust_tbl.CUST_TYPE
	 *
	 * @return the value of cust_tbl.CUST_TYPE
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public String getCustType() {
		return custType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cust_tbl.CUST_TYPE
	 *
	 * @param custType the value for cust_tbl.CUST_TYPE
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public void setCustType(String custType) {
		this.custType = custType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cust_tbl.CUST_MONEY
	 *
	 * @return the value of cust_tbl.CUST_MONEY
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public String getCustMoney() {
		return custMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cust_tbl.CUST_MONEY
	 *
	 * @param custMoney the value for cust_tbl.CUST_MONEY
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public void setCustMoney(String custMoney) {
		this.custMoney = custMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cust_tbl.CUST_INVOICE_NO
	 *
	 * @return the value of cust_tbl.CUST_INVOICE_NO
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public String getCustInvoiceNo() {
		return custInvoiceNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cust_tbl.CUST_INVOICE_NO
	 *
	 * @param custInvoiceNo the value for cust_tbl.CUST_INVOICE_NO
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public void setCustInvoiceNo(String custInvoiceNo) {
		this.custInvoiceNo = custInvoiceNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cust_tbl.CUST_INFOR_SECURITY
	 *
	 * @return the value of cust_tbl.CUST_INFOR_SECURITY
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public boolean getCustInforSecurity() {
		return custInforSecurity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cust_tbl.CUST_INFOR_SECURITY
	 *
	 * @param custInforSecurity the value for cust_tbl.CUST_INFOR_SECURITY
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public void setCustInforSecurity(boolean custInforSecurity) {
		this.custInforSecurity = custInforSecurity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cust_tbl.CUST_DISPATCH
	 *
	 * @return the value of cust_tbl.CUST_DISPATCH
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public boolean getCustDispatch() {
		return custDispatch;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cust_tbl.CUST_DISPATCH
	 *
	 * @param custDispatch the value for cust_tbl.CUST_DISPATCH
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public void setCustDispatch(boolean custDispatch) {
		this.custDispatch = custDispatch;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cust_tbl.CUST_EMPNUM
	 *
	 * @return the value of cust_tbl.CUST_EMPNUM
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public Integer getCustEmpnum() {
		return custEmpnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cust_tbl.CUST_EMPNUM
	 *
	 * @param custEmpnum the value for cust_tbl.CUST_EMPNUM
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public void setCustEmpnum(Integer custEmpnum) {
		this.custEmpnum = custEmpnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cust_tbl.CUST_STARTDT
	 *
	 * @return the value of cust_tbl.CUST_STARTDT
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public LocalDateTime getCustStartdt() {
		return custStartdt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cust_tbl.CUST_STARTDT
	 *
	 * @param custStartdt the value for cust_tbl.CUST_STARTDT
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public void setCustStartdt(LocalDateTime custStartdt) {
		this.custStartdt = custStartdt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cust_tbl.CUST_ANNUALSALE
	 *
	 * @return the value of cust_tbl.CUST_ANNUALSALE
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public String getCustAnnualsale() {
		return custAnnualsale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cust_tbl.CUST_ANNUALSALE
	 *
	 * @param custAnnualsale the value for cust_tbl.CUST_ANNUALSALE
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public void setCustAnnualsale(String custAnnualsale) {
		this.custAnnualsale = custAnnualsale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cust_tbl.CUST_COMPANYREP
	 *
	 * @return the value of cust_tbl.CUST_COMPANYREP
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public String getCustCompanyrep() {
		return custCompanyrep;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cust_tbl.CUST_COMPANYREP
	 *
	 * @param custCompanyrep the value for cust_tbl.CUST_COMPANYREP
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public void setCustCompanyrep(String custCompanyrep) {
		this.custCompanyrep = custCompanyrep;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cust_tbl.CUST_RMK1
	 *
	 * @return the value of cust_tbl.CUST_RMK1
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public String getCustRmk1() {
		return custRmk1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cust_tbl.CUST_RMK1
	 *
	 * @param custRmk1 the value for cust_tbl.CUST_RMK1
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public void setCustRmk1(String custRmk1) {
		this.custRmk1 = custRmk1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cust_tbl.CUST_RMK2
	 *
	 * @return the value of cust_tbl.CUST_RMK2
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public String getCustRmk2() {
		return custRmk2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cust_tbl.CUST_RMK2
	 *
	 * @param custRmk2 the value for cust_tbl.CUST_RMK2
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public void setCustRmk2(String custRmk2) {
		this.custRmk2 = custRmk2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cust_tbl.CUST_CLOSEDT
	 *
	 * @return the value of cust_tbl.CUST_CLOSEDT
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public String getCustClosedt() {
		return custClosedt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cust_tbl.CUST_CLOSEDT
	 *
	 * @param custClosedt the value for cust_tbl.CUST_CLOSEDT
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public void setCustClosedt(String custClosedt) {
		this.custClosedt = custClosedt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cust_tbl.CUST_PAYDT
	 *
	 * @return the value of cust_tbl.CUST_PAYDT
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public String getCustPaydt() {
		return custPaydt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cust_tbl.CUST_PAYDT
	 *
	 * @param custPaydt the value for cust_tbl.CUST_PAYDT
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public void setCustPaydt(String custPaydt) {
		this.custPaydt = custPaydt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cust_tbl.CUST_ORDERDT
	 *
	 * @return the value of cust_tbl.CUST_ORDERDT
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public String getCustOrderdt() {
		return custOrderdt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cust_tbl.CUST_ORDERDT
	 *
	 * @param custOrderdt the value for cust_tbl.CUST_ORDERDT
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public void setCustOrderdt(String custOrderdt) {
		this.custOrderdt = custOrderdt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cust_tbl.CUST_GETDT
	 *
	 * @return the value of cust_tbl.CUST_GETDT
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public String getCustGetdt() {
		return custGetdt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cust_tbl.CUST_GETDT
	 *
	 * @param custGetdt the value for cust_tbl.CUST_GETDT
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public void setCustGetdt(String custGetdt) {
		this.custGetdt = custGetdt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cust_tbl.CUST_GETCDT
	 *
	 * @return the value of cust_tbl.CUST_GETCDT
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public String getCustGetcdt() {
		return custGetcdt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cust_tbl.CUST_GETCDT
	 *
	 * @param custGetcdt the value for cust_tbl.CUST_GETCDT
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public void setCustGetcdt(String custGetcdt) {
		this.custGetcdt = custGetcdt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cust_tbl.CUST_ORDERGDT
	 *
	 * @return the value of cust_tbl.CUST_ORDERGDT
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public String getCustOrdergdt() {
		return custOrdergdt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cust_tbl.CUST_ORDERGDT
	 *
	 * @param custOrdergdt the value for cust_tbl.CUST_ORDERGDT
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public void setCustOrdergdt(String custOrdergdt) {
		this.custOrdergdt = custOrdergdt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cust_tbl.BANK_CD
	 *
	 * @return the value of cust_tbl.BANK_CD
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public String getBankCd() {
		return bankCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cust_tbl.BANK_CD
	 *
	 * @param bankCd the value for cust_tbl.BANK_CD
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public void setBankCd(String bankCd) {
		this.bankCd = bankCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cust_tbl.BANK_CHRCD
	 *
	 * @return the value of cust_tbl.BANK_CHRCD
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public String getBankChrcd() {
		return bankChrcd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cust_tbl.BANK_CHRCD
	 *
	 * @param bankChrcd the value for cust_tbl.BANK_CHRCD
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public void setBankChrcd(String bankChrcd) {
		this.bankChrcd = bankChrcd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cust_tbl.CUST_BANK_NM
	 *
	 * @return the value of cust_tbl.CUST_BANK_NM
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public String getCustBankNm() {
		return custBankNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cust_tbl.CUST_BANK_NM
	 *
	 * @param custBankNm the value for cust_tbl.CUST_BANK_NM
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public void setCustBankNm(String custBankNm) {
		this.custBankNm = custBankNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cust_tbl.CUST_BRANCH_CD
	 *
	 * @return the value of cust_tbl.CUST_BRANCH_CD
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public String getCustBranchCd() {
		return custBranchCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cust_tbl.CUST_BRANCH_CD
	 *
	 * @param custBranchCd the value for cust_tbl.CUST_BRANCH_CD
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public void setCustBranchCd(String custBranchCd) {
		this.custBranchCd = custBranchCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cust_tbl.CUST_DEPOSITTYPE
	 *
	 * @return the value of cust_tbl.CUST_DEPOSITTYPE
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public String getCustDeposittype() {
		return custDeposittype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cust_tbl.CUST_DEPOSITTYPE
	 *
	 * @param custDeposittype the value for cust_tbl.CUST_DEPOSITTYPE
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public void setCustDeposittype(String custDeposittype) {
		this.custDeposittype = custDeposittype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cust_tbl.CUST_BRANCHCD
	 *
	 * @return the value of cust_tbl.CUST_BRANCHCD
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public String getCustBranchcd() {
		return custBranchCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cust_tbl.CUST_BRANCHCD
	 *
	 * @param custBranchcd the value for cust_tbl.CUST_BRANCHCD
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public void setCustBranchcd(String custBranchcd) {
		this.custBranchCd = custBranchcd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cust_tbl.CUST_ACCOUNTNO
	 *
	 * @return the value of cust_tbl.CUST_ACCOUNTNO
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public Integer getCustAccountno() {
		return custAccountno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cust_tbl.CUST_ACCOUNTNO
	 *
	 * @param custAccountno the value for cust_tbl.CUST_ACCOUNTNO
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public void setCustAccountno(Integer custAccountno) {
		this.custAccountno = custAccountno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cust_tbl.CUST_NOMINEE
	 *
	 * @return the value of cust_tbl.CUST_NOMINEE
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public String getCustNominee() {
		return custNominee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cust_tbl.CUST_NOMINEE
	 *
	 * @param custNominee the value for cust_tbl.CUST_NOMINEE
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public void setCustNominee(String custNominee) {
		this.custNominee = custNominee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cust_tbl.CUST_CRD_USR
	 *
	 * @return the value of cust_tbl.CUST_CRD_USR
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public String getCustCrdUsr() {
		return custCrdUsr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cust_tbl.CUST_CRD_USR
	 *
	 * @param custCrdUsr the value for cust_tbl.CUST_CRD_USR
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public void setCustCrdUsr(String custCrdUsr) {
		this.custCrdUsr = custCrdUsr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cust_tbl.CUST_CRD_DT
	 *
	 * @return the value of cust_tbl.CUST_CRD_DT
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public LocalDateTime getCustCrdDt() {
		return custCrdDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cust_tbl.CUST_CRD_DT
	 *
	 * @param localDateTime the value for cust_tbl.CUST_CRD_DT
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public void setCustCrdDt(LocalDateTime localDateTime) {
		this.custCrdDt = localDateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cust_tbl.CUST_UPD_USR
	 *
	 * @return the value of cust_tbl.CUST_UPD_USR
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public String getCustUpdUsr() {
		return custUpdUsr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cust_tbl.CUST_UPD_USR
	 *
	 * @param custUpdUsr the value for cust_tbl.CUST_UPD_USR
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public void setCustUpdUsr(String custUpdUsr) {
		this.custUpdUsr = custUpdUsr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cust_tbl.CUST_UPD_DT
	 *
	 * @return the value of cust_tbl.CUST_UPD_DT
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public LocalDateTime getCustUpdDt() {
		return custUpdDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cust_tbl.CUST_UPD_DT
	 *
	 * @param localDateTime the value for cust_tbl.CUST_UPD_DT
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	public void setCustUpdDt(LocalDateTime localDateTime) {
		this.custUpdDt = localDateTime;

	}

	public CustInfo(String custId, String custNm, String custKn, String custPhone, boolean custDelflg, String custFax,
			String custWeb, String custPostno, String custAddress, String custType, String custMoney,
			String custInvoiceNo, boolean custInforSecurity, boolean custDispatch, Integer custEmpnum,
			LocalDateTime custStartdt, String custAnnualsale, String custCompanyrep, String custRmk1, String custRmk2,
			String custClosedt, String custPaydt, String custOrderdt, String custGetdt, String custGetcdt,
			String custOrdergdt, String bankCd, String bankChrcd, String custBankNm, String custBranchCd,
			String custDeposittype, String custBranchcd2, Integer custAccountno, String custNominee, String custCrdUsr,
			LocalDateTime custCrdDt, String custUpdUsr, LocalDateTime custUpdDt) {
		super();
		this.custId = custId;
		this.custNm = custNm;
		this.custKn = custKn;
		this.custPhone = custPhone;
		this.custDelflg = custDelflg;
		this.custFax = custFax;
		this.custWeb = custWeb;
		this.custPostno = custPostno;
		this.custAddress = custAddress;
		this.custType = custType;
		this.custMoney = custMoney;
		this.custInvoiceNo = custInvoiceNo;
		this.custInforSecurity = custInforSecurity;
		this.custDispatch = custDispatch;
		this.custEmpnum = custEmpnum;
		this.custStartdt = custStartdt;
		this.custAnnualsale = custAnnualsale;
		this.custCompanyrep = custCompanyrep;
		this.custRmk1 = custRmk1;
		this.custRmk2 = custRmk2;
		this.custClosedt = custClosedt;
		this.custPaydt = custPaydt;
		this.custOrderdt = custOrderdt;
		this.custGetdt = custGetdt;
		this.custGetcdt = custGetcdt;
		this.custOrdergdt = custOrdergdt;
		this.bankCd = bankCd;
		this.bankChrcd = bankChrcd;
		this.custBankNm = custBankNm;
		this.custBranchCd = custBranchCd;
		this.custDeposittype = custDeposittype;
		custBranchCd = custBranchcd2;
		this.custAccountno = custAccountno;
		this.custNominee = custNominee;
		this.custCrdUsr = custCrdUsr;
		this.custCrdDt = custCrdDt;
		this.custUpdUsr = custUpdUsr;
		this.custUpdDt = custUpdDt;
	}

	public CustInfo(String custType, String bankCd, String bankChrcd, String custBankNm, String custBranchNm,
			String custDeposittype, String custBranchCd, Integer custAccountno, String custNominee) {
		super();
		this.custType = custType;
		this.bankCd = bankCd;
		this.bankChrcd = bankChrcd;
		this.custBankNm = custBankNm;
		this.custBranchNm = custBranchNm;
		this.custDeposittype = custDeposittype;
		this.custBranchCd = custBranchCd;
		this.custAccountno = custAccountno;
		this.custNominee = custNominee;
	}

	@Override
	public String toString() {
		return "CustInfo [custId=" + custId + ", custNm=" + custNm + ", custKn=" + custKn + ", custPhone=" + custPhone
				+ ", custDelflg=" + custDelflg + ", custFax=" + custFax + ", custWeb=" + custWeb + ", custPostno="
				+ custPostno + ", custAddress=" + custAddress + ", custType=" + custType + ", custMoney=" + custMoney
				+ ", custInvoiceNo=" + custInvoiceNo + ", custInforSecurity=" + custInforSecurity + ", custDispatch="
				+ custDispatch + ", custEmpnum=" + custEmpnum + ", custStartdt=" + custStartdt + ", custAnnualsale="
				+ custAnnualsale + ", custCompanyrep=" + custCompanyrep + ", custRmk1=" + custRmk1 + ", custRmk2="
				+ custRmk2 + ", custClosedt=" + custClosedt + ", custPaydt=" + custPaydt + ", custOrderdt="
				+ custOrderdt + ", custGetdt=" + custGetdt + ", custGetcdt=" + custGetcdt + ", custOrdergdt="
				+ custOrdergdt + ", bankCd=" + bankCd + ", bankChrcd=" + bankChrcd + ", custBankNm=" + custBankNm
				+ ", custBranchCd=" + custBranchCd + ", custDeposittype=" + custDeposittype + ", custBranchcd="
				+ custBranchCd + ", custAccountno=" + custAccountno + ", custNominee=" + custNominee + ", custCrdUsr="
				+ custCrdUsr + ", custCrdDt=" + custCrdDt + ", custUpdUsr=" + custUpdUsr + ", custUpdDt=" + custUpdDt
				+ "]";
	}

	public CustInfo(String custId, String custNm, String custPhone, boolean custDelflg, String custAddress,
			String custCrdUsr, LocalDateTime custCrdDt, String custUpdUsr, LocalDateTime custUpdDt) {
		super();
		this.custId = custId;
		this.custNm = custNm;
		this.custPhone = custPhone;
		this.custDelflg = custDelflg;
		this.custAddress = custAddress;
		this.custCrdUsr = custCrdUsr;
		this.custCrdDt = custCrdDt;
		this.custUpdUsr = custUpdUsr;
		this.custUpdDt = custUpdDt;
	}

	public CustInfo() {
		super();
	}

	public String getCustBranchNm() {
		return custBranchNm;
	}

	public void setCustBranchNm(String custBranchNm) {
		this.custBranchNm = custBranchNm;
	}
}