package com.itec.pojo;

import java.time.LocalDateTime;
import java.util.List;

import org.springframework.stereotype.Component;

@Component
public class MangInfo {
	private List<MangInfo> mangInfo;

	public List<MangInfo> getMangInfo() {
		return mangInfo;
	}

	public void setMangInfo(List<MangInfo> mangInfo) {
		this.mangInfo = mangInfo;
	}

	private String managerCd;
	private String managerChrcd;
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column mang_tbl.MANAGER_NM
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	private String managerNm;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column mang_tbl.MANAGER_CUST_ID
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	private String managerCustId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column mang_tbl.MANAGER_PNO
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	private String managerPno;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column mang_tbl.MANAGER_JOB
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	private String managerJob;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column mang_tbl.MANAGER_RMK
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	private String managerRmk;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column mang_tbl.MANAGER_MAIL
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	private String managerMail;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column mang_tbl.MANAGER_CRD_USR
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	private String managerCrdUsr;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column mang_tbl.MANAGER_CRD_DT
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	private LocalDateTime managerCrdDt;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column mang_tbl.MANAGER_UPD_USR
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	private String managerUpdUsr;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column mang_tbl.MANAGER_UPD_DT
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */
	private LocalDateTime managerUpdDt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column mang_tbl.MANAGER_NM
	 *
	 * @return the value of mang_tbl.MANAGER_NM
	 *
	 * @mbg.generated Sun Oct 13 00:26:12 HKT 2024
	 */

	public MangInfo() {
		super();
	}

	@Override
	public String toString() {
		return "MangInfo [managerCd=" + managerCd + ", managerChrcd=" + managerChrcd + ", managerNm=" + managerNm
				+ ", managerCustId=" + managerCustId + ", managerPno=" + managerPno + ", managerJob=" + managerJob
				+ ", managerRmk=" + managerRmk + ", managerMail=" + managerMail + ", managerCrdUsr=" + managerCrdUsr
				+ ", managerCrdDt=" + managerCrdDt + ", managerUpdUsr=" + managerUpdUsr + ", managerUpdDt="
				+ managerUpdDt + "]";
	}

	public MangInfo(String managerCd, String managerChrcd, String managerNm, String managerCustId, String managerPno,
			String managerJob, String managerRmk, String managerMail, String managerCrdUsr, LocalDateTime managerCrdDt,
			String managerUpdUsr, LocalDateTime managerUpdDt) {
		super();
		this.managerCd = managerCd;
		this.managerChrcd = managerChrcd;
		this.managerNm = managerNm;
		this.managerCustId = managerCustId;
		this.managerPno = managerPno;
		this.managerJob = managerJob;
		this.managerRmk = managerRmk;
		this.managerMail = managerMail;
		this.managerCrdUsr = managerCrdUsr;
		this.managerCrdDt = managerCrdDt;
		this.managerUpdUsr = managerUpdUsr;
		this.managerUpdDt = managerUpdDt;
	}

	public String getManagerCd() {
		return managerCd;
	}

	public void setManagerCd(String managerCd) {
		this.managerCd = managerCd;
	}

	public String getManagerChrcd() {
		return managerChrcd;
	}

	public void setManagerChrcd(String managerChrcd) {
		this.managerChrcd = managerChrcd;
	}

	public String getManagerNm() {
		return managerNm;
	}

	public void setManagerNm(String managerNm) {
		this.managerNm = managerNm;
	}

	public String getManagerCustId() {
		return managerCustId;
	}

	public void setManagerCustId(String managerCustId) {
		this.managerCustId = managerCustId;
	}

	public String getManagerPno() {
		return managerPno;
	}

	public void setManagerPno(String managerPno) {
		this.managerPno = managerPno;
	}

	public String getManagerJob() {
		return managerJob;
	}

	public void setManagerJob(String managerJob) {
		this.managerJob = managerJob;
	}

	public String getManagerRmk() {
		return managerRmk;
	}

	public void setManagerRmk(String managerRmk) {
		this.managerRmk = managerRmk;
	}

	public String getManagerMail() {
		return managerMail;
	}

	public void setManagerMail(String managerMail) {
		this.managerMail = managerMail;
	}

	public String getManagerCrdUsr() {
		return managerCrdUsr;
	}

	public void setManagerCrdUsr(String managerCrdUsr) {
		this.managerCrdUsr = managerCrdUsr;
	}

	public LocalDateTime getManagerCrdDt() {
		return managerCrdDt;
	}

	public void setManagerCrdDt(LocalDateTime localDateTime) {
		this.managerCrdDt = localDateTime;
	}

	public String getManagerUpdUsr() {
		return managerUpdUsr;
	}

	public void setManagerUpdUsr(String managerUpdUsr) {
		this.managerUpdUsr = managerUpdUsr;
	}

	public LocalDateTime getManagerUpdDt() {
		return managerUpdDt;
	}

	public void setManagerUpdDt(LocalDateTime localDateTime) {
		this.managerUpdDt = localDateTime;
	}

}