package com.itec.pojo;

import org.springframework.stereotype.Component;

@Component
public class OperateKey {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column M_OPERATE_TBL.OPER_ID
	 *
	 * @mbg.generated Fri Dec 13 14:58:51 HKT 2024
	 */
	private Long operId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column M_OPERATE_TBL.OPER_NO
	 *
	 * @mbg.generated Fri Dec 13 14:58:51 HKT 2024
	 */
	private String operNo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column M_OPERATE_TBL.OPER_ID
	 *
	 * @return the value of M_OPERATE_TBL.OPER_ID
	 *
	 * @mbg.generated Fri Dec 13 14:58:51 HKT 2024
	 */
	public Long getOperId() {
		return operId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column M_OPERATE_TBL.OPER_ID
	 *
	 * @param operId the value for M_OPERATE_TBL.OPER_ID
	 *
	 * @mbg.generated Fri Dec 13 14:58:51 HKT 2024
	 */
	public void setOperId(Long operId) {
		this.operId = operId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column M_OPERATE_TBL.OPER_NO
	 *
	 * @return the value of M_OPERATE_TBL.OPER_NO
	 *
	 * @mbg.generated Fri Dec 13 14:58:51 HKT 2024
	 */
	public String getOperNo() {
		return operNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column M_OPERATE_TBL.OPER_NO
	 *
	 * @param operNo the value for M_OPERATE_TBL.OPER_NO
	 *
	 * @mbg.generated Fri Dec 13 14:58:51 HKT 2024
	 */
	public void setOperNo(String operNo) {
		this.operNo = operNo;
	}
}