package com.itec.pojo;

import java.util.Date;

public class Staff {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_TBL.STAFF_ID
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    private Long staffId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_TBL.STAFF_NO
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    private String staffNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_TBL.STAFF_NM
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    private String staffNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_TBL.STAFF_KN
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    private String staffKn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_TBL.STAFF_ALPHABET
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    private String staffAlphabet;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_TBL.STAFF_SEX
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    private String staffSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_TBL.STAFF_DELFLG
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    private String staffDelflg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_TBL.STAFF_COUNTRY
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    private String staffCountry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_TBL.STAFF_BIRTHPLACE
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    private String staffBirthplace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_TBL.STAFF_CLS
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    private String staffCls;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_TBL.STAFF_COMPANY
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    private String staffCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_TBL.STAFF_SALESSTATUS
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    private String staffSalesstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_TBL.STAFF_GROUP
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    private String staffGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_TBL.STAFF_POST
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    private String staffPost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_TBL.STAFF_RMK1
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    private String staffRmk1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_TBL.STAFF_AGE
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    private Byte staffAge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_TBL.STAFF_MYNO
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    private String staffMyno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_TBL.STAFF_PHONENO
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    private String staffPhoneno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_TBL.STAFF_RESIDENCECARD
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    private String staffResidencecard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_TBL.STAFF_RESTYPE
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    private String staffRestype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_TBL.STAFF_CARDENDDT
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    private Date staffCardenddt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_TBL.STAFF_BIRTHDT
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    private Date staffBirthdt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_TBL.STAFF_POSTNO
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    private String staffPostno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_TBL.STAFF_ADDRESS
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    private String staffAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_TBL.STAFF_INDT
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    private Date staffIndt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_TBL.STAFF_OUTDT
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    private Date staffOutdt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_TBL.STAFF_MAIL
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    private String staffMail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_TBL.STAFF_NEARESTSTATION
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    private String staffNeareststation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_TBL.STAFF_RESUME
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    private String staffResume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_TBL.STAFF_INSURANCENO
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    private String staffInsuranceno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_TBL.STAFF_INSURANCETYPE
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    private String staffInsurancetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_TBL.STAFF_SPECIALTY
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    private String staffSpecialty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_TBL.STAFF_RMK2
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    private String staffRmk2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_TBL.STAFF_PHOTO
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    private String staffPhoto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_TBL.STAFF_EMERGENCYCALL
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    private String staffEmergencycall;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_TBL.CUST_CRD_USR
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    private String custCrdUsr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_TBL.STAFF_CRE_DT
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    private Date staffCreDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_TBL.CUST_UPD_USR
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    private String custUpdUsr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_TBL.STAFF_UPD_DT
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    private Date staffUpdDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_TBL.STAFF_DELDT
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    private Date staffDeldt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_TBL.STAFF_ID
     *
     * @return the value of STAFF_TBL.STAFF_ID
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public Long getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_TBL.STAFF_ID
     *
     * @param staffId the value for STAFF_TBL.STAFF_ID
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public void setStaffId(Long staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_TBL.STAFF_NO
     *
     * @return the value of STAFF_TBL.STAFF_NO
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public String getStaffNo() {
        return staffNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_TBL.STAFF_NO
     *
     * @param staffNo the value for STAFF_TBL.STAFF_NO
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public void setStaffNo(String staffNo) {
        this.staffNo = staffNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_TBL.STAFF_NM
     *
     * @return the value of STAFF_TBL.STAFF_NM
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public String getStaffNm() {
        return staffNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_TBL.STAFF_NM
     *
     * @param staffNm the value for STAFF_TBL.STAFF_NM
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public void setStaffNm(String staffNm) {
        this.staffNm = staffNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_TBL.STAFF_KN
     *
     * @return the value of STAFF_TBL.STAFF_KN
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public String getStaffKn() {
        return staffKn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_TBL.STAFF_KN
     *
     * @param staffKn the value for STAFF_TBL.STAFF_KN
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public void setStaffKn(String staffKn) {
        this.staffKn = staffKn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_TBL.STAFF_ALPHABET
     *
     * @return the value of STAFF_TBL.STAFF_ALPHABET
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public String getStaffAlphabet() {
        return staffAlphabet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_TBL.STAFF_ALPHABET
     *
     * @param staffAlphabet the value for STAFF_TBL.STAFF_ALPHABET
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public void setStaffAlphabet(String staffAlphabet) {
        this.staffAlphabet = staffAlphabet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_TBL.STAFF_SEX
     *
     * @return the value of STAFF_TBL.STAFF_SEX
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public String getStaffSex() {
        return staffSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_TBL.STAFF_SEX
     *
     * @param staffSex the value for STAFF_TBL.STAFF_SEX
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public void setStaffSex(String staffSex) {
        this.staffSex = staffSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_TBL.STAFF_DELFLG
     *
     * @return the value of STAFF_TBL.STAFF_DELFLG
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public String getStaffDelflg() {
        return staffDelflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_TBL.STAFF_DELFLG
     *
     * @param staffDelflg the value for STAFF_TBL.STAFF_DELFLG
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public void setStaffDelflg(String staffDelflg) {
        this.staffDelflg = staffDelflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_TBL.STAFF_COUNTRY
     *
     * @return the value of STAFF_TBL.STAFF_COUNTRY
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public String getStaffCountry() {
        return staffCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_TBL.STAFF_COUNTRY
     *
     * @param staffCountry the value for STAFF_TBL.STAFF_COUNTRY
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public void setStaffCountry(String staffCountry) {
        this.staffCountry = staffCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_TBL.STAFF_BIRTHPLACE
     *
     * @return the value of STAFF_TBL.STAFF_BIRTHPLACE
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public String getStaffBirthplace() {
        return staffBirthplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_TBL.STAFF_BIRTHPLACE
     *
     * @param staffBirthplace the value for STAFF_TBL.STAFF_BIRTHPLACE
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public void setStaffBirthplace(String staffBirthplace) {
        this.staffBirthplace = staffBirthplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_TBL.STAFF_CLS
     *
     * @return the value of STAFF_TBL.STAFF_CLS
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public String getStaffCls() {
        return staffCls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_TBL.STAFF_CLS
     *
     * @param staffCls the value for STAFF_TBL.STAFF_CLS
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public void setStaffCls(String staffCls) {
        this.staffCls = staffCls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_TBL.STAFF_COMPANY
     *
     * @return the value of STAFF_TBL.STAFF_COMPANY
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public String getStaffCompany() {
        return staffCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_TBL.STAFF_COMPANY
     *
     * @param staffCompany the value for STAFF_TBL.STAFF_COMPANY
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public void setStaffCompany(String staffCompany) {
        this.staffCompany = staffCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_TBL.STAFF_SALESSTATUS
     *
     * @return the value of STAFF_TBL.STAFF_SALESSTATUS
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public String getStaffSalesstatus() {
        return staffSalesstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_TBL.STAFF_SALESSTATUS
     *
     * @param staffSalesstatus the value for STAFF_TBL.STAFF_SALESSTATUS
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public void setStaffSalesstatus(String staffSalesstatus) {
        this.staffSalesstatus = staffSalesstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_TBL.STAFF_GROUP
     *
     * @return the value of STAFF_TBL.STAFF_GROUP
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public String getStaffGroup() {
        return staffGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_TBL.STAFF_GROUP
     *
     * @param staffGroup the value for STAFF_TBL.STAFF_GROUP
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public void setStaffGroup(String staffGroup) {
        this.staffGroup = staffGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_TBL.STAFF_POST
     *
     * @return the value of STAFF_TBL.STAFF_POST
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public String getStaffPost() {
        return staffPost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_TBL.STAFF_POST
     *
     * @param staffPost the value for STAFF_TBL.STAFF_POST
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public void setStaffPost(String staffPost) {
        this.staffPost = staffPost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_TBL.STAFF_RMK1
     *
     * @return the value of STAFF_TBL.STAFF_RMK1
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public String getStaffRmk1() {
        return staffRmk1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_TBL.STAFF_RMK1
     *
     * @param staffRmk1 the value for STAFF_TBL.STAFF_RMK1
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public void setStaffRmk1(String staffRmk1) {
        this.staffRmk1 = staffRmk1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_TBL.STAFF_AGE
     *
     * @return the value of STAFF_TBL.STAFF_AGE
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public Byte getStaffAge() {
        return staffAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_TBL.STAFF_AGE
     *
     * @param staffAge the value for STAFF_TBL.STAFF_AGE
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public void setStaffAge(Byte staffAge) {
        this.staffAge = staffAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_TBL.STAFF_MYNO
     *
     * @return the value of STAFF_TBL.STAFF_MYNO
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public String getStaffMyno() {
        return staffMyno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_TBL.STAFF_MYNO
     *
     * @param staffMyno the value for STAFF_TBL.STAFF_MYNO
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public void setStaffMyno(String staffMyno) {
        this.staffMyno = staffMyno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_TBL.STAFF_PHONENO
     *
     * @return the value of STAFF_TBL.STAFF_PHONENO
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public String getStaffPhoneno() {
        return staffPhoneno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_TBL.STAFF_PHONENO
     *
     * @param staffPhoneno the value for STAFF_TBL.STAFF_PHONENO
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public void setStaffPhoneno(String staffPhoneno) {
        this.staffPhoneno = staffPhoneno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_TBL.STAFF_RESIDENCECARD
     *
     * @return the value of STAFF_TBL.STAFF_RESIDENCECARD
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public String getStaffResidencecard() {
        return staffResidencecard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_TBL.STAFF_RESIDENCECARD
     *
     * @param staffResidencecard the value for STAFF_TBL.STAFF_RESIDENCECARD
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public void setStaffResidencecard(String staffResidencecard) {
        this.staffResidencecard = staffResidencecard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_TBL.STAFF_RESTYPE
     *
     * @return the value of STAFF_TBL.STAFF_RESTYPE
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public String getStaffRestype() {
        return staffRestype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_TBL.STAFF_RESTYPE
     *
     * @param staffRestype the value for STAFF_TBL.STAFF_RESTYPE
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public void setStaffRestype(String staffRestype) {
        this.staffRestype = staffRestype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_TBL.STAFF_CARDENDDT
     *
     * @return the value of STAFF_TBL.STAFF_CARDENDDT
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public Date getStaffCardenddt() {
        return staffCardenddt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_TBL.STAFF_CARDENDDT
     *
     * @param staffCardenddt the value for STAFF_TBL.STAFF_CARDENDDT
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public void setStaffCardenddt(Date staffCardenddt) {
        this.staffCardenddt = staffCardenddt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_TBL.STAFF_BIRTHDT
     *
     * @return the value of STAFF_TBL.STAFF_BIRTHDT
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public Date getStaffBirthdt() {
        return staffBirthdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_TBL.STAFF_BIRTHDT
     *
     * @param staffBirthdt the value for STAFF_TBL.STAFF_BIRTHDT
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public void setStaffBirthdt(Date staffBirthdt) {
        this.staffBirthdt = staffBirthdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_TBL.STAFF_POSTNO
     *
     * @return the value of STAFF_TBL.STAFF_POSTNO
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public String getStaffPostno() {
        return staffPostno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_TBL.STAFF_POSTNO
     *
     * @param staffPostno the value for STAFF_TBL.STAFF_POSTNO
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public void setStaffPostno(String staffPostno) {
        this.staffPostno = staffPostno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_TBL.STAFF_ADDRESS
     *
     * @return the value of STAFF_TBL.STAFF_ADDRESS
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public String getStaffAddress() {
        return staffAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_TBL.STAFF_ADDRESS
     *
     * @param staffAddress the value for STAFF_TBL.STAFF_ADDRESS
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public void setStaffAddress(String staffAddress) {
        this.staffAddress = staffAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_TBL.STAFF_INDT
     *
     * @return the value of STAFF_TBL.STAFF_INDT
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public Date getStaffIndt() {
        return staffIndt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_TBL.STAFF_INDT
     *
     * @param staffIndt the value for STAFF_TBL.STAFF_INDT
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public void setStaffIndt(Date staffIndt) {
        this.staffIndt = staffIndt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_TBL.STAFF_OUTDT
     *
     * @return the value of STAFF_TBL.STAFF_OUTDT
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public Date getStaffOutdt() {
        return staffOutdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_TBL.STAFF_OUTDT
     *
     * @param staffOutdt the value for STAFF_TBL.STAFF_OUTDT
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public void setStaffOutdt(Date staffOutdt) {
        this.staffOutdt = staffOutdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_TBL.STAFF_MAIL
     *
     * @return the value of STAFF_TBL.STAFF_MAIL
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public String getStaffMail() {
        return staffMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_TBL.STAFF_MAIL
     *
     * @param staffMail the value for STAFF_TBL.STAFF_MAIL
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public void setStaffMail(String staffMail) {
        this.staffMail = staffMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_TBL.STAFF_NEARESTSTATION
     *
     * @return the value of STAFF_TBL.STAFF_NEARESTSTATION
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public String getStaffNeareststation() {
        return staffNeareststation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_TBL.STAFF_NEARESTSTATION
     *
     * @param staffNeareststation the value for STAFF_TBL.STAFF_NEARESTSTATION
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public void setStaffNeareststation(String staffNeareststation) {
        this.staffNeareststation = staffNeareststation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_TBL.STAFF_RESUME
     *
     * @return the value of STAFF_TBL.STAFF_RESUME
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public String getStaffResume() {
        return staffResume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_TBL.STAFF_RESUME
     *
     * @param staffResume the value for STAFF_TBL.STAFF_RESUME
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public void setStaffResume(String staffResume) {
        this.staffResume = staffResume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_TBL.STAFF_INSURANCENO
     *
     * @return the value of STAFF_TBL.STAFF_INSURANCENO
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public String getStaffInsuranceno() {
        return staffInsuranceno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_TBL.STAFF_INSURANCENO
     *
     * @param staffInsuranceno the value for STAFF_TBL.STAFF_INSURANCENO
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public void setStaffInsuranceno(String staffInsuranceno) {
        this.staffInsuranceno = staffInsuranceno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_TBL.STAFF_INSURANCETYPE
     *
     * @return the value of STAFF_TBL.STAFF_INSURANCETYPE
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public String getStaffInsurancetype() {
        return staffInsurancetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_TBL.STAFF_INSURANCETYPE
     *
     * @param staffInsurancetype the value for STAFF_TBL.STAFF_INSURANCETYPE
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public void setStaffInsurancetype(String staffInsurancetype) {
        this.staffInsurancetype = staffInsurancetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_TBL.STAFF_SPECIALTY
     *
     * @return the value of STAFF_TBL.STAFF_SPECIALTY
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public String getStaffSpecialty() {
        return staffSpecialty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_TBL.STAFF_SPECIALTY
     *
     * @param staffSpecialty the value for STAFF_TBL.STAFF_SPECIALTY
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public void setStaffSpecialty(String staffSpecialty) {
        this.staffSpecialty = staffSpecialty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_TBL.STAFF_RMK2
     *
     * @return the value of STAFF_TBL.STAFF_RMK2
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public String getStaffRmk2() {
        return staffRmk2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_TBL.STAFF_RMK2
     *
     * @param staffRmk2 the value for STAFF_TBL.STAFF_RMK2
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public void setStaffRmk2(String staffRmk2) {
        this.staffRmk2 = staffRmk2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_TBL.STAFF_PHOTO
     *
     * @return the value of STAFF_TBL.STAFF_PHOTO
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public String getStaffPhoto() {
        return staffPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_TBL.STAFF_PHOTO
     *
     * @param staffPhoto the value for STAFF_TBL.STAFF_PHOTO
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public void setStaffPhoto(String staffPhoto) {
        this.staffPhoto = staffPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_TBL.STAFF_EMERGENCYCALL
     *
     * @return the value of STAFF_TBL.STAFF_EMERGENCYCALL
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public String getStaffEmergencycall() {
        return staffEmergencycall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_TBL.STAFF_EMERGENCYCALL
     *
     * @param staffEmergencycall the value for STAFF_TBL.STAFF_EMERGENCYCALL
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public void setStaffEmergencycall(String staffEmergencycall) {
        this.staffEmergencycall = staffEmergencycall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_TBL.CUST_CRD_USR
     *
     * @return the value of STAFF_TBL.CUST_CRD_USR
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public String getCustCrdUsr() {
        return custCrdUsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_TBL.CUST_CRD_USR
     *
     * @param custCrdUsr the value for STAFF_TBL.CUST_CRD_USR
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public void setCustCrdUsr(String custCrdUsr) {
        this.custCrdUsr = custCrdUsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_TBL.STAFF_CRE_DT
     *
     * @return the value of STAFF_TBL.STAFF_CRE_DT
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public Date getStaffCreDt() {
        return staffCreDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_TBL.STAFF_CRE_DT
     *
     * @param staffCreDt the value for STAFF_TBL.STAFF_CRE_DT
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public void setStaffCreDt(Date staffCreDt) {
        this.staffCreDt = staffCreDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_TBL.CUST_UPD_USR
     *
     * @return the value of STAFF_TBL.CUST_UPD_USR
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public String getCustUpdUsr() {
        return custUpdUsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_TBL.CUST_UPD_USR
     *
     * @param custUpdUsr the value for STAFF_TBL.CUST_UPD_USR
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public void setCustUpdUsr(String custUpdUsr) {
        this.custUpdUsr = custUpdUsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_TBL.STAFF_UPD_DT
     *
     * @return the value of STAFF_TBL.STAFF_UPD_DT
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public Date getStaffUpdDt() {
        return staffUpdDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_TBL.STAFF_UPD_DT
     *
     * @param staffUpdDt the value for STAFF_TBL.STAFF_UPD_DT
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public void setStaffUpdDt(Date staffUpdDt) {
        this.staffUpdDt = staffUpdDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_TBL.STAFF_DELDT
     *
     * @return the value of STAFF_TBL.STAFF_DELDT
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public Date getStaffDeldt() {
        return staffDeldt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_TBL.STAFF_DELDT
     *
     * @param staffDeldt the value for STAFF_TBL.STAFF_DELDT
     *
     * @mbg.generated Wed Nov 27 12:33:24 HKT 2024
     */
    public void setStaffDeldt(Date staffDeldt) {
        this.staffDeldt = staffDeldt;
    }
}