package com.itec.pojo;

import java.util.Date;

public class User {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user_tbl.USER_ID
	 *
	 * @mbg.generated Thu Nov 14 21:49:59 HKT 2024
	 */
	private String userId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user_tbl.USER_NM
	 *
	 * @mbg.generated Thu Nov 14 21:49:59 HKT 2024
	 */
	private String userNm;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user_tbl.USER_PWD
	 *
	 * @mbg.generated Thu Nov 14 21:49:59 HKT 2024
	 */
	private String userPwd;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user_tbl.USER_ROLE
	 *
	 * @mbg.generated Thu Nov 14 21:49:59 HKT 2024
	 */
	private Byte userRole;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user_tbl.USER_MAILADDRESS
	 *
	 * @mbg.generated Thu Nov 14 21:49:59 HKT 2024
	 */
	private String userMailaddress;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user_tbl.USER_PW_EXPIRATION
	 *
	 * @mbg.generated Thu Nov 14 21:49:59 HKT 2024
	 */

	private Date userPwExpiration;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user_tbl.USER_EX_PW_DAY
	 *
	 * @mbg.generated Thu Nov 14 21:49:59 HKT 2024
	 */

	private Date userExPwDay;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user_tbl.USER_DEPARTMENT
	 *
	 * @mbg.generated Thu Nov 14 21:49:59 HKT 2024
	 */
	private String userDepartment;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user_tbl.USER_LOCK_FLG
	 *
	 * @mbg.generated Thu Nov 14 21:49:59 HKT 2024
	 */
	private String userLockFlg;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user_tbl.USER_DEL_FLG
	 *
	 * @mbg.generated Thu Nov 14 21:49:59 HKT 2024
	 */
	private String userDelFlg;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user_tbl.MANAGER_CRD_USR
	 *
	 * @mbg.generated Thu Nov 14 21:49:59 HKT 2024
	 */
	private String managerCrdUsr;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user_tbl.MANAGER_CRD_DT
	 *
	 * @mbg.generated Thu Nov 14 21:49:59 HKT 2024
	 */
	private Date managerCrdDt;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user_tbl.MANAGER_UPD_USR
	 *
	 * @mbg.generated Thu Nov 14 21:49:59 HKT 2024
	 */
	private String managerUpdUsr;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user_tbl.MANAGER_UPD_DT
	 *
	 * @mbg.generated Thu Nov 14 21:49:59 HKT 2024
	 */
	private Date managerUpdDt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user_tbl.USER_ID
	 *
	 * @return the value of user_tbl.USER_ID
	 *
	 * @mbg.generated Thu Nov 14 21:49:59 HKT 2024
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user_tbl.USER_ID
	 *
	 * @param userId the value for user_tbl.USER_ID
	 *
	 * @mbg.generated Thu Nov 14 21:49:59 HKT 2024
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user_tbl.USER_NM
	 *
	 * @return the value of user_tbl.USER_NM
	 *
	 * @mbg.generated Thu Nov 14 21:49:59 HKT 2024
	 */
	public String getUserNm() {
		return userNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user_tbl.USER_NM
	 *
	 * @param userNm the value for user_tbl.USER_NM
	 *
	 * @mbg.generated Thu Nov 14 21:49:59 HKT 2024
	 */
	public void setUserNm(String userNm) {
		this.userNm = userNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user_tbl.USER_PWD
	 *
	 * @return the value of user_tbl.USER_PWD
	 *
	 * @mbg.generated Thu Nov 14 21:49:59 HKT 2024
	 */
	public String getUserPwd() {
		return userPwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user_tbl.USER_PWD
	 *
	 * @param userPwd the value for user_tbl.USER_PWD
	 *
	 * @mbg.generated Thu Nov 14 21:49:59 HKT 2024
	 */
	public void setUserPwd(String userPwd) {
		this.userPwd = userPwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user_tbl.USER_ROLE
	 *
	 * @return the value of user_tbl.USER_ROLE
	 *
	 * @mbg.generated Thu Nov 14 21:49:59 HKT 2024
	 */
	public Byte getUserRole() {
		return userRole;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user_tbl.USER_ROLE
	 *
	 * @param userRole the value for user_tbl.USER_ROLE
	 *
	 * @mbg.generated Thu Nov 14 21:49:59 HKT 2024
	 */
	public void setUserRole(Byte userRole) {
		this.userRole = userRole;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user_tbl.USER_MAILADDRESS
	 *
	 * @return the value of user_tbl.USER_MAILADDRESS
	 *
	 * @mbg.generated Thu Nov 14 21:49:59 HKT 2024
	 */
	public String getUserMailaddress() {
		return userMailaddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user_tbl.USER_MAILADDRESS
	 *
	 * @param userMailaddress the value for user_tbl.USER_MAILADDRESS
	 *
	 * @mbg.generated Thu Nov 14 21:49:59 HKT 2024
	 */
	public void setUserMailaddress(String userMailaddress) {
		this.userMailaddress = userMailaddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user_tbl.USER_PW_EXPIRATION
	 *
	 * @return the value of user_tbl.USER_PW_EXPIRATION
	 *
	 * @mbg.generated Thu Nov 14 21:49:59 HKT 2024
	 */
	public Date getUserPwExpiration() {
		return userPwExpiration;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user_tbl.USER_PW_EXPIRATION
	 *
	 * @param userPwExpiration the value for user_tbl.USER_PW_EXPIRATION
	 *
	 * @mbg.generated Thu Nov 14 21:49:59 HKT 2024
	 */
	public void setUserPwExpiration(Date userPwExpiration) {
		this.userPwExpiration = userPwExpiration;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user_tbl.USER_EX_PW_DAY
	 *
	 * @return the value of user_tbl.USER_EX_PW_DAY
	 *
	 * @mbg.generated Thu Nov 14 21:49:59 HKT 2024
	 */
	public Date getUserExPwDay() {
		return userExPwDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user_tbl.USER_EX_PW_DAY
	 *
	 * @param userExPwDay the value for user_tbl.USER_EX_PW_DAY
	 *
	 * @mbg.generated Thu Nov 14 21:49:59 HKT 2024
	 */
	public void setUserExPwDay(Date userExPwDay) {
		this.userExPwDay = userExPwDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user_tbl.USER_DEPARTMENT
	 *
	 * @return the value of user_tbl.USER_DEPARTMENT
	 *
	 * @mbg.generated Thu Nov 14 21:49:59 HKT 2024
	 */
	public String getUserDepartment() {
		return userDepartment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user_tbl.USER_DEPARTMENT
	 *
	 * @param userDepartment the value for user_tbl.USER_DEPARTMENT
	 *
	 * @mbg.generated Thu Nov 14 21:49:59 HKT 2024
	 */
	public void setUserDepartment(String userDepartment) {
		this.userDepartment = userDepartment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user_tbl.USER_LOCK_FLG
	 *
	 * @return the value of user_tbl.USER_LOCK_FLG
	 *
	 * @mbg.generated Thu Nov 14 21:49:59 HKT 2024
	 */
	public String getUserLockFlg() {
		return userLockFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user_tbl.USER_LOCK_FLG
	 *
	 * @param userLockFlg the value for user_tbl.USER_LOCK_FLG
	 *
	 * @mbg.generated Thu Nov 14 21:49:59 HKT 2024
	 */
	public void setUserLockFlg(String userLockFlg) {
		this.userLockFlg = userLockFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user_tbl.USER_DEL_FLG
	 *
	 * @return the value of user_tbl.USER_DEL_FLG
	 *
	 * @mbg.generated Thu Nov 14 21:49:59 HKT 2024
	 */
	public String getUserDelFlg() {
		return userDelFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user_tbl.USER_DEL_FLG
	 *
	 * @param userDelFlg the value for user_tbl.USER_DEL_FLG
	 *
	 * @mbg.generated Thu Nov 14 21:49:59 HKT 2024
	 */
	public void setUserDelFlg(String userDelFlg) {
		this.userDelFlg = userDelFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user_tbl.MANAGER_CRD_USR
	 *
	 * @return the value of user_tbl.MANAGER_CRD_USR
	 *
	 * @mbg.generated Thu Nov 14 21:49:59 HKT 2024
	 */
	public String getManagerCrdUsr() {
		return managerCrdUsr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user_tbl.MANAGER_CRD_USR
	 *
	 * @param managerCrdUsr the value for user_tbl.MANAGER_CRD_USR
	 *
	 * @mbg.generated Thu Nov 14 21:49:59 HKT 2024
	 */
	public void setManagerCrdUsr(String managerCrdUsr) {
		this.managerCrdUsr = managerCrdUsr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user_tbl.MANAGER_CRD_DT
	 *
	 * @return the value of user_tbl.MANAGER_CRD_DT
	 *
	 * @mbg.generated Thu Nov 14 21:49:59 HKT 2024
	 */
	public Date getManagerCrdDt() {
		return managerCrdDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user_tbl.MANAGER_CRD_DT
	 *
	 * @param managerCrdDt the value for user_tbl.MANAGER_CRD_DT
	 *
	 * @mbg.generated Thu Nov 14 21:49:59 HKT 2024
	 */
	public void setManagerCrdDt(Date managerCrdDt) {
		this.managerCrdDt = managerCrdDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user_tbl.MANAGER_UPD_USR
	 *
	 * @return the value of user_tbl.MANAGER_UPD_USR
	 *
	 * @mbg.generated Thu Nov 14 21:49:59 HKT 2024
	 */
	public String getManagerUpdUsr() {
		return managerUpdUsr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user_tbl.MANAGER_UPD_USR
	 *
	 * @param managerUpdUsr the value for user_tbl.MANAGER_UPD_USR
	 *
	 * @mbg.generated Thu Nov 14 21:49:59 HKT 2024
	 */
	public void setManagerUpdUsr(String managerUpdUsr) {
		this.managerUpdUsr = managerUpdUsr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user_tbl.MANAGER_UPD_DT
	 *
	 * @return the value of user_tbl.MANAGER_UPD_DT
	 *
	 * @mbg.generated Thu Nov 14 21:49:59 HKT 2024
	 */
	public Date getManagerUpdDt() {
		return managerUpdDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user_tbl.MANAGER_UPD_DT
	 *
	 * @param managerUpdDt the value for user_tbl.MANAGER_UPD_DT
	 *
	 * @mbg.generated Thu Nov 14 21:49:59 HKT 2024
	 */
	public void setManagerUpdDt(Date managerUpdDt) {
		this.managerUpdDt = managerUpdDt;
	}
}